export const EVENTS = {
    TEST: 'TEST',
    SEND_MESSAGE: 'SEND_MESSAGE',
    BROADCAST_MESSAGE: 'BROADCAST_MESSAGE',
    SEND_USER: 'SEND_USER',
    BROADCAST_USER: 'BROADCAST_USER',
    DISCONNECT: 'disconnect',
    BROADCAST_USERS_LIST: 'EVENTS.BROADCAST_USERS_LIST',
    BROADCAST_MESSAGE_HISTORY: 'BROADCAST_MESSAGE_HISTORY',
    DISABLE_USER_INPUT:  'DISABLE_USER_INPUT'
};