export const EVENTS = {
    SEND_STATE: 'SEND_STATE',
    BROADCAST_STATE: 'BROADCAST_STATE',
    SEND_USER: 'SEND_USER',
    LIKE_COUNTER: 'LIKE_COUNTER',
    INCREASE_LIKE: 'INCREASE_LIKE',
    BROADCAST_ALL_STATES: 'BROADCAST_ALL_STATES',
    DELETE_STATE: 'DELETE_STATE'
}