export const EVENTS = {
    SEND_STATE: 'SEND_STATE',
    BROADCAST_STATE: 'BROADCAST_STATE',
    LIKE_COUNTER: 'LIKE_COUNTER',
    INCREASE_LIKE: 'INCREASE_LIKE',
    BROADCAST_ALL_STATES: 'BROADCAST_ALL_STATES',
    DELETE_STATE: 'DELETE_STATE',
    EXPIRATED_TOKEN: 'EXPIRATE_TOKEN',
    DO_LOGIN: 'DO_LOGIN',
    SUCESS_LOGIN: 'SUCESS_LOGIN',
    FAILED_LOGIN: 'FAILED_LOGIN',
    BROADCAST_ALL_STATES_FIRST: 'BROADCAST_ALL_STATES_FIRST',
    BROADCAST_COMMON_USERS: 'BROADCAST_COMMON_USERS'
}